version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - revive

  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

formatters:
  enable:
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/jorge-sanchez/cloud-commerce
