// Code generated by tygo. DO NOT EDIT.

//////////
// source: apitypes.go
/*
apitypes.go owns the wire contract for this service's HTTP surface.
Every 200/201 body is an exported, JSON-tagged struct declared here —
never gin.H. gin.H stays fine for error bodies ({code, message} from
pkg/errors).
*/

/**
 * VariantResponse is the single-variant wire shape. Prices are integer
 * minor units; the display currency comes from store settings.
 */
export interface VariantResponse {
  id: string;
  sku: string;
  option_values: string[];
  price_cents: number /* int64 */;
}
/**
 * ProductResponse is the single-product wire shape.
 */
export interface ProductResponse {
  id: string;
  title: string;
  description: string;
  status: string;
  options: string[];
  variants: VariantResponse[];
  created_at: string /* RFC 3339 */;
  updated_at: string /* RFC 3339 */;
}
/**
 * ListProductsResponse is the blessed offset-pagination envelope:
 * {items, total, page, page_size}.
 */
export interface ListProductsResponse {
  items: ProductResponse[];
  total: number /* int */;
  page: number /* int */;
  page_size: number /* int */;
}
/**
 * CollectionResponse is the single-collection wire shape. ProductIDs is
 * populated on single fetches, empty in list responses.
 */
export interface CollectionResponse {
  id: string;
  title: string;
  handle: string;
  product_ids: string[];
  created_at: string /* RFC 3339 */;
  updated_at: string /* RFC 3339 */;
}
/**
 * ListCollectionsResponse is the blessed offset-pagination envelope.
 */
export interface ListCollectionsResponse {
  items: CollectionResponse[];
  total: number /* int */;
  page: number /* int */;
  page_size: number /* int */;
}

//////////
// source: collection_handler.go

/**
 * CollectionHandler exposes the collection HTTP surface.
 */
export interface CollectionHandler {
}

//////////
// source: product_handler.go
/*
Package handler holds the HTTP adapters (Gin). Handlers translate between
the wire contract (apitypes.go) and the application service — no business
rules here.
*/

/**
 * ProductHandler exposes the catalog HTTP surface. Both owner and staff
 * manage the catalog — no role gate here (unlike staff management).
 */
export interface ProductHandler {
}
