// Code generated by tygo. DO NOT EDIT.

//////////
// source: apitypes.go
/*
apitypes.go owns the wire contract for this service's HTTP surface.
Every 200/201 body is an exported, JSON-tagged struct declared here —
never gin.H. gin.H stays fine for error bodies ({code, message} from
pkg/errors).
*/

/**
 * VariantResponse is the single-variant wire shape. Prices are integer
 * minor units; the display currency comes from store settings.
 */
export interface VariantResponse {
  id: string;
  sku: string;
  option_values: string[];
  price_cents: number /* int64 */;
}
/**
 * ImageResponse is the single-image wire shape. URL is composed from the
 * configured media base at read time (position 0 is the primary/thumbnail).
 */
export interface ImageResponse {
  id: string;
  url: string;
  alt_text: string;
  position: number /* int */;
  width: number /* int */;
  height: number /* int */;
}
/**
 * ProductResponse is the single-product wire shape.
 */
export interface ProductResponse {
  id: string;
  title: string;
  description: string;
  status: string;
  options: string[];
  variants: VariantResponse[];
  images: ImageResponse[];
  created_at: string /* RFC 3339 */;
  updated_at: string /* RFC 3339 */;
}
/**
 * SignImageUploadResponse hands the admin a direct-to-storage upload URL and
 * the object key it must send back to finalize the image.
 */
export interface SignImageUploadResponse {
  upload_url: string;
  storage_key: string;
  method: string;
}
/**
 * ListProductsResponse is the blessed offset-pagination envelope:
 * {items, total, page, page_size}.
 */
export interface ListProductsResponse {
  items: ProductResponse[];
  total: number /* int */;
  page: number /* int */;
  page_size: number /* int */;
}
/**
 * PublicVariantResponse is the storefront's purchasable-variant lookup —
 * what a cart needs to snapshot a line.
 */
export interface PublicVariantResponse {
  variant_id: string;
  product_id: string;
  product_title: string;
  sku: string;
  option_values: string[];
  price_cents: number /* int64 */;
}
/**
 * CollectionResponse is the single-collection wire shape. ProductIDs is
 * populated on single fetches, empty in list responses.
 */
export interface CollectionResponse {
  id: string;
  title: string;
  handle: string;
  product_ids: string[];
  created_at: string /* RFC 3339 */;
  updated_at: string /* RFC 3339 */;
}
/**
 * ListCollectionsResponse is the blessed offset-pagination envelope.
 */
export interface ListCollectionsResponse {
  items: CollectionResponse[];
  total: number /* int */;
  page: number /* int */;
  page_size: number /* int */;
}

//////////
// source: collection_handler.go

/**
 * CollectionHandler exposes the collection HTTP surface.
 */
export interface CollectionHandler {
}

//////////
// source: product_handler.go
/*
Package handler holds the HTTP adapters (Gin). Handlers translate between
the wire contract (apitypes.go) and the application service — no business
rules here.
*/

/**
 * ProductHandler exposes the catalog HTTP surface. Both owner and staff
 * manage the catalog — no role gate here (unlike staff management).
 */
export interface ProductHandler {
}
/**
 * HandlerOption configures optional dependencies on the handler.
 */
export type HandlerOption = any;
