// Code generated by tygo. DO NOT EDIT.

//////////
// source: apitypes.go
/*
apitypes.go owns the wire contract for this service's HTTP surface.
Every 200/201 body is an exported, JSON-tagged struct declared here —
never gin.H. gin.H stays fine for error bodies ({code, message} from
pkg/errors).
*/

/**
 * LocationResponse is the single-location wire shape.
 */
export interface LocationResponse {
  id: string;
  name: string;
  is_default: boolean;
  created_at: string /* RFC 3339 */;
}
/**
 * ListLocationsResponse is the blessed offset envelope (page always 1 —
 * location lists are small; the envelope keeps the shape forward-compatible).
 */
export interface ListLocationsResponse {
  items: LocationResponse[];
  total: number /* int */;
  page: number /* int */;
  page_size: number /* int */;
}
/**
 * StockLevelResponse is the single-stock-level wire shape.
 */
export interface StockLevelResponse {
  id: string;
  location_id: string;
  variant_id: string;
  sku: string;
  on_hand: number /* int64 */;
  updated_at: string /* RFC 3339 */;
}
/**
 * ListStockResponse is the blessed offset-pagination envelope:
 * {items, total, page, page_size}.
 */
export interface ListStockResponse {
  items: StockLevelResponse[];
  total: number /* int */;
  page: number /* int */;
  page_size: number /* int */;
}

//////////
// source: pubsub_handler.go

/**
 * PushTokenValidator validates the Google-signed OIDC token on a Pub/Sub
 * push request and returns the caller's service-account email. Implemented
 * by idtokenValidator in cmd/main.go (google.golang.org/api/idtoken).
 */
export type PushTokenValidator = any;
/**
 * PubSubHandler receives Pub/Sub push deliveries (ADR-002 amendment: Pub/Sub
 * is the relay transport). Delivery is at-least-once — the service layer is
 * idempotent. A non-2xx response makes Pub/Sub redeliver.
 */
export interface PubSubHandler {
}
/**
 * pushRequest is the Pub/Sub push wire format; Data is base64 in JSON,
 * which encoding/json decodes into []byte transparently.
 */

//////////
// source: stock_handler.go
/*
Package handler holds the HTTP adapters (Gin). Handlers translate between
the wire contract (apitypes.go) and the application service — no business
rules here.
*/

/**
 * StockHandler exposes the inventory HTTP surface. Both owner and staff
 * manage stock — no role gate here.
 */
export interface StockHandler {
}
