// Code generated by tygo. DO NOT EDIT.

//////////
// source: apitypes.go
/*
apitypes.go owns the wire contract for this service's HTTP surface.
Every 200/201 body is an exported, JSON-tagged struct declared here —
never gin.H. gin.H stays fine for error bodies ({code, message} from
pkg/errors).
*/

/**
 * MerchantResponse is the single-merchant wire shape.
 */
export interface MerchantResponse {
  id: string;
  name: string;
  status: string;
  created_at: string /* RFC 3339 */;
}
/**
 * UserResponse is the merchant-user wire shape. Never carries the hash.
 */
export interface UserResponse {
  id: string;
  email: string;
  role: string;
}
/**
 * SessionResponse is returned by sign-up (201) and login (200).
 */
export interface SessionResponse {
  token: string;
  merchant: MerchantResponse;
  user: UserResponse;
}
/**
 * MeResponse is the authenticated identity surface.
 */
export interface MeResponse {
  merchant: MerchantResponse;
  user: UserResponse;
}
/**
 * ListStaffResponse is the blessed offset envelope for the staff list
 * (page is always 1 — staff lists are small; the envelope keeps the shape
 * forward-compatible).
 */
export interface ListStaffResponse {
  items: UserResponse[];
  total: number /* int */;
  page: number /* int */;
  page_size: number /* int */;
}
/**
 * APIKeyResponse is the key metadata shape. Key (plaintext) is present
 * only in the creation response — it is never retrievable again.
 */
export interface APIKeyResponse {
  id: string;
  name: string;
  key?: string;
  revoked: boolean;
  created_at: string /* RFC 3339 */;
}
/**
 * ListAPIKeysResponse is the blessed offset envelope (page always 1).
 */
export interface ListAPIKeysResponse {
  items: APIKeyResponse[];
  total: number /* int */;
  page: number /* int */;
  page_size: number /* int */;
}
/**
 * APITokenResponse is the key-exchange result.
 */
export interface APITokenResponse {
  token: string;
}
/**
 * PublicStoreResponse is the unauthenticated storefront lookup shape —
 * only what a buyer client needs to browse and display prices.
 */
export interface PublicStoreResponse {
  id: string;
  name: string;
  handle: string;
  currency: string;
  timezone: string;
}
/**
 * StoreResponse is the store profile wire shape.
 */
export interface StoreResponse {
  id: string;
  name: string;
  handle: string;
  status: string;
  currency: string;
  timezone: string;
  support_email: string;
  created_at: string /* RFC 3339 */;
  updated_at: string /* RFC 3339 */;
}

//////////
// source: merchant_handler.go
/*
Package handler holds the HTTP adapters (Gin). Handlers translate between
the wire contract (apitypes.go) and the application service — no business
rules here.
*/

/**
 * MerchantHandler exposes the identity HTTP surface.
 */
export interface MerchantHandler {
}
