// Code generated by tygo. DO NOT EDIT.

//////////
// source: apitypes.go
/*
apitypes.go owns the wire contract for this service's HTTP surface.
Every 200/201 body is an exported, JSON-tagged struct declared here —
never gin.H. gin.H stays fine for error bodies ({code, message} from
pkg/errors).
*/

/**
 * ItemResponse is a priced cart/order line (snapshot, minor units).
 */
export interface ItemResponse {
  variant_id: string;
  sku: string;
  title: string;
  price_cents: number /* int64 */;
  qty: number /* int64 */;
}
/**
 * CartResponse is the buyer's cart wire shape. The cart ID is the buyer's
 * capability — treat it like a secret.
 */
export interface CartResponse {
  id: string;
  tenant_id: string;
  currency: string;
  items: ItemResponse[];
  total_cents: number /* int64 */;
}
/**
 * OrderResponse is the order wire shape (buyer checkout result and
 * merchant order views).
 */
export interface OrderResponse {
  id: string;
  number: number /* int64 */;
  email: string;
  currency: string;
  items: ItemResponse[];
  total_cents: number /* int64 */;
  status: string;
  tracking_number: string;
  carrier: string;
  created_at: string /* RFC 3339 */;
}
/**
 * PaymentIntentResponse is the provider handoff for the buyer client.
 */
export interface PaymentIntentResponse {
  reference: string;
  client_secret: string;
}
/**
 * ListOrdersResponse is the blessed offset-pagination envelope:
 * {items, total, page, page_size}.
 */
export interface ListOrdersResponse {
  items: OrderResponse[];
  total: number /* int */;
  page: number /* int */;
  page_size: number /* int */;
}
/**
 * DailySalesResponse is one day of revenue.
 */
export interface DailySalesResponse {
  date: string;
  revenue_cents: number /* int64 */;
  orders: number /* int */;
}
/**
 * TopProductResponse is a best-selling variant.
 */
export interface TopProductResponse {
  sku: string;
  title: string;
  units: number /* int64 */;
  revenue_cents: number /* int64 */;
}
/**
 * AnalyticsSummaryResponse is the merchant analytics read.
 */
export interface AnalyticsSummaryResponse {
  currency: string;
  days: DailySalesResponse[];
  top_products: TopProductResponse[];
}

//////////
// source: order_handler.go
/*
Package handler holds the HTTP adapters (Gin). Handlers translate between
the wire contract (apitypes.go) and the application service — no business
rules here.
*/

/**
 * OrderHandler exposes both surfaces: the buyer cart/checkout/payment
 * routes (public, capability-based) and the merchant order views (authed).
 */
export interface OrderHandler {
}

//////////
// source: stripe_webhook_handler.go

/**
 * StripeWebhookHandler reconciles payments without buyer polling (#25):
 * Stripe signs each delivery with the endpoint's signing secret; a verified
 * payment_intent.succeeded marks the order paid. Deliveries are
 * at-least-once and can race the buyer's own confirm — MarkPaidIfPayable
 * makes both paths idempotent.
 */
export interface StripeWebhookHandler {
}
