// Code generated by tygo. DO NOT EDIT.

//////////
// source: apitypes.go
/*
apitypes.go owns the wire contract for this service's HTTP surface.
Every 200/201 body is an exported, JSON-tagged struct declared here —
never gin.H. gin.H stays fine for error bodies ({code, message} from
pkg/errors).
*/

/**
 * ItemResponse is a priced cart/order line (snapshot, minor units).
 */
export interface ItemResponse {
  variant_id: string;
  sku: string;
  title: string;
  price_cents: number /* int64 */;
  qty: number /* int64 */;
}
/**
 * CartResponse is the buyer's cart wire shape. The cart ID is the buyer's
 * capability — treat it like a secret.
 */
export interface CartResponse {
  id: string;
  tenant_id: string;
  currency: string;
  items: ItemResponse[];
  total_cents: number /* int64 */;
}
/**
 * OrderResponse is the order wire shape (buyer checkout result and
 * merchant order views).
 */
export interface OrderResponse {
  id: string;
  number: number /* int64 */;
  email: string;
  currency: string;
  items: ItemResponse[];
  total_cents: number /* int64 */;
  status: string;
  created_at: string /* RFC 3339 */;
}
/**
 * ListOrdersResponse is the blessed offset-pagination envelope:
 * {items, total, page, page_size}.
 */
export interface ListOrdersResponse {
  items: OrderResponse[];
  total: number /* int */;
  page: number /* int */;
  page_size: number /* int */;
}

//////////
// source: order_handler.go
/*
Package handler holds the HTTP adapters (Gin). Handlers translate between
the wire contract (apitypes.go) and the application service — no business
rules here.
*/

/**
 * OrderHandler exposes both surfaces: the buyer cart/checkout routes
 * (public, capability-based) and the merchant order views (authed).
 */
export interface OrderHandler {
}
